const CONFIG = {
  ROOT_DRIVE_FOLDER_ID: 'PUT_ROOT_DRIVE_FOLDER_ID_HERE',
  SHEET_ID: 'PUT_GOOGLE_SHEET_ID_HERE',
  DOC_TEMPLATE_ID: 'PUT_GOOGLE_DOC_TEMPLATE_ID_HERE',
  TIMEZONE: 'Europe/Istanbul',
  MAX_UPLOAD_MB: 15,
  TOKEN_TTL_DAYS: 30
};

const SHEETS = {
  SETTINGS: 'SETTINGS',
  GROUPS: 'GROUPS',
  FORM_FIELDS: 'FORM_FIELDS',
  PERSONNEL: 'PERSONNEL',
  DOCUMENT_LOG: 'DOCUMENT_LOG',
  LINKS: 'LINKS',
  DOCUMENTS: 'DOCUMENTS'
};
